<template>
  <div class="agent-config-mobile-list" :aria-busy="loading">
    <div v-if="error" class="agent-config-list-error" role="alert"><p>{{ error }}</p><p v-if="items.length">下方显示上次成功加载的内容。</p><el-button :loading="loading" @click="emit('retry')">重新加载</el-button></div>
    <p v-if="loading" class="agent-config-list-empty" role="status">正在加载{{ label }}…</p>
    <p v-else-if="!error && !items.length" class="agent-config-list-empty">{{ keyword ? '没有匹配内容，请调整关键词' : `暂无${label}` }}</p>
    <article v-for="(item, index) in items" :key="item.id || item.sandbox_id || item.name || index" class="agent-config-resource">
      <button class="agent-config-resource-main" :disabled="!canRead" @click="emit('action', 'view', item)"><span class="agent-config-resource-kind">{{ label }}</span><h3>{{ item.display_name || item.name || item.sandbox_id || '未命名' }}</h3><p v-if="item.description">{{ item.description }}</p><p v-else-if="item.model">模型：{{ item.model }}</p><p v-else-if="item.image">{{ item.image }}</p><span class="agent-config-resource-link">查看详情 →</span></button>
      <div class="agent-config-resource-tags"><span v-if="item.llm_provider">{{ item.llm_provider }}</span><span v-if="item.type">{{ item.type }}</span><span v-if="item.tools?.length">{{ item.tools.length }} 个工具</span><span v-if="item.enabled_tools?.length">{{ item.enabled_tools.length }} 个可用工具</span><span v-if="item.skills?.length">{{ item.skills.length }} 项技能</span><span v-if="item.parameters?.length">{{ item.parameters.length }} 个参数</span><span v-if="item.sandbox_status || item.status">{{ item.sandbox_status || item.status }}</span><span v-if="item.always">始终注入</span></div>
      <p v-if="item.updated_at || item.created_at" class="agent-config-resource-time">{{ formatDateTime(item.updated_at || item.created_at) }}</p>
      <div v-if="canEdit || canDelete || (kind === 'sandboxes' && item.host_port)" class="agent-config-resource-actions"><el-button v-if="canEdit" @click="emit('action', 'edit', item)">编辑配置</el-button><el-button v-if="kind === 'sandboxes' && item.host_port && canRead" @click="emit('action', 'browser', item)">浏览器</el-button><el-button v-if="kind === 'sandboxes' && item.host_port && canRead" @click="emit('action', 'code', item)">代码环境</el-button><el-button v-if="canDelete" type="danger" plain @click="emit('action', 'delete', item)">{{ kind === 'sandboxes' ? '销毁' : '删除' }}</el-button></div>
    </article>
    <div v-if="pagination && pagination.total > 0" class="agent-config-list-pages"><p>共 {{ pagination.total }} 项 · 第 {{ pagination.page }} 页</p><el-pagination :current-page="pagination.page" :page-size="pagination.pageSize" :total="pagination.total" :pager-count="5" layout="prev, pager, next" :disabled="loading" @current-change="emit('page', $event)" /></div>
  </div>
</template>
<script setup>
import { formatDateTime } from '@/utils/action'
defineProps({ items: { type: Array, default: () => [] }, kind: String, label: String, loading: Boolean, error: String, keyword: String, pagination: Object, canRead: Boolean, canEdit: Boolean, canDelete: Boolean })
const emit = defineEmits(['action', 'retry', 'page'])
</script>
<style scoped>
.agent-config-mobile-list{display:grid;gap:12px;min-width:0}.agent-config-resource{background:white;border:1px solid #e2e8f0;border-radius:16px;padding:16px;min-width:0}.agent-config-resource-main{display:block;text-align:left;width:100%;min-height:70px}.agent-config-resource-main:disabled{color:#64748b}.agent-config-resource-kind{font-size:11px;color:#64748b}.agent-config-resource-main h3{font-size:18px;font-weight:650;line-height:1.5;overflow-wrap:anywhere;margin:6px 0}.agent-config-resource-main p{font-size:14px;line-height:1.7;color:#64748b;display:-webkit-box;-webkit-line-clamp:3;-webkit-box-orient:vertical;overflow:hidden;overflow-wrap:anywhere}.agent-config-resource-link{display:block;color:#2563eb;font-size:13px;margin:12px 0}.agent-config-resource-tags{display:flex;gap:6px;flex-wrap:wrap}.agent-config-resource-tags>span{font-size:12px;line-height:1.5;padding:3px 7px;background:#f1f5f9;border-radius:6px;overflow-wrap:anywhere}.agent-config-resource-time{font-size:12px;color:#64748b;margin-top:12px}.agent-config-resource-actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.agent-config-resource-actions :deep(.el-button){margin:0;min-height:44px;flex:1;min-width:95px}.agent-config-list-empty{text-align:center;color:#64748b;padding:40px 8px;font-size:14px}.agent-config-list-error{padding:14px;border:1px solid #fed7aa;background:#fff7ed;border-radius:12px;font-size:14px;line-height:1.7}.agent-config-list-pages{text-align:center;padding:12px 0}.agent-config-list-pages p{color:#64748b;font-size:12px;margin:0 0 8px}.agent-config-list-pages :deep(.el-pagination){justify-content:center}
</style>
